### ISSUE TITLE
ticket9

### ISSUE THREAD

**Issue by turovkv** [vladnosiv/hse-spb-conspects-2020#107]
Про RAII написано не то.
читаем [википедию](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_%D1%80%D0%B5%D1%81%D1%83%D1%80%D1%81%D0%B0_%D0%B5%D1%81%D1%82%D1%8C_%D0%B8%D0%BD%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F) и понимаем, что RAII, это когда new/openfile/.. скрыты в конструкторе, а delete/closefile/... скрыты в деструкторе. 
RAII переводится как получение/захват ресурса есть инициализация (а освобождение ресурса это удаление объекта, вызов деструктора)

@hwanglight

**Comment by stray-polina-study** [comment]
Ну нет, у меня тоже самое написано
Проинициализировав поля мы захватываем все ресурсы, которые нам нужны. При этом, если какой-то ресурс не удалось захватить (например, не удалось открыть файл) кидается исключение
Деструктор - удаляет объект - > освобождает ресурсы

@turovkv

**Comment by turovkv** [comment]
Про захват ресурсов в билете ни слова

@hwanglight

**Comment by stray-polina-study** [comment]
Потому что это частный случай
Ну я могу добавить, но это же не главное в этом принципе
@turovkv

**Comment by psurkov** [comment]
Обновил раздел про RAII, написал про захват
