### ISSUE TITLE
ticket2

### ISSUE THREAD

**Issue by KaperD** [vladnosiv/hse-spb-conspects-2020#84]
Пример про static и анонимные пространства имен ничего не иллюстрирует, так как здесь всего одна единица трансляции, да и программа выводит 239, а не 82, как написано. Думаю, лучше как-нибудь так: 

* Static и анонимные пространства имен.
    * Internal linkage позволяет использовать объект/функцию/класс только в той единице трансляции, в которой они объявлены и определены, что позволяет избежать коллизий.
        
        file1.cpp

        ```C++
        static int var = 82; // Передаю привет Гимназии №82 города Краснодара
        int foo() { return var; } 
        ```

        file2.cpp

        ```C++
        static int var = 239;
        int bar() { return var; }
        ```

        main.cpp
        ```C++
        #include <iostream>
        int foo();
        int bar();

        int main() {
            std::cout << foo() << std::endl; // 82
            std::cout << bar() << std::endl; // 239
            return 0;
        }
        ```

    * Выше был показан сишный подход, в плюсах решили, что для internal linkage будут использовать анонимные пространства имен. Также анонимные пространства имен позволяют делать internal linkage для типов (классов, структур), что не позволяет static

        ```C++
        namespace {

        int var = 82;

        class A { int x { 0 }; }

        void f() { }

        }
        ```

        В плюсах лучше всегда использовать анонимные пространства имен.

**Comment by psurkov** [comment]
@vladnosiv

**Comment by vladnosiv** [comment]
Спасибо, исправил!
