### ISSUE TITLE
ticket1

### ISSUE THREAD

**Issue by turovkv** [vladnosiv/hse-spb-conspects-2020#89]
Про static inline const/constexpr:

если не писать inline, то необходимо эту константу определить ровно в одном cpp файле (иначе ошбка компиляции).

если пишем inline, то больше ничего определять не нужно.

C++17 - если написали static constexpr ... , то слово inline автоматически вставится
```
struct Foo {
    static inline const std::string NO = "NO"
    static inline constexpr char YES[] = "YES"
}
inline const std::string NO = "NO"
inline constexpr char YES[] = "YES"
```
последние 2 строчки не относятся к Foo

**Comment by psurkov** [comment]
@kot239

**Comment by KaperD** [comment]
В C++-17 можно и определить внутри без inline, inline нужен, если нужно не константную переменную сразу же определить 

```Cpp
struct S {
    static const int a = 1;
    static constexpr int b = 2;
    static inline constexpr int c = 3;
    static inline const int d = 4;
    static inline int e = 5;
};

int main() {
    std::cout << S::a << ' ' << S::b << ' ' << S::c << ' ' << S::d << ' ' << S::e << '\n';
    
    return 0;
}
```

**Comment by KaperD** [comment]
А, нет, вру, это только с примитивными типами
